default_stages: [commit]
repos:
  - repo: https://github.com/yingzi113/pre-commit-hooks
    rev: 5863e162f1bed1f63eeb716e77d622ff8e3d9af9
    hooks:
    - id: check-case-conflict
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    - id: autopep8
      args: [-i, --global-config=.flake8, -v, --ignore=E402]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
      args:
      - --ignore=E501,E402
      exclude: package_hub/_modules/init_host.py
    - id: check-docstring-first
    - id: trailing-whitespace
    - id: check-ast
    - id: check-json
    - id: check-yaml
exclude: migrations
