# Generated by Django 3.1.4 on 2021-09-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='环境名称', max_length=256, verbose_name='环境名称')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'omp_env',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='软删除')),
                ('instance_name', models.CharField(help_text='实例名', max_length=64, verbose_name='实例名')),
                ('ip', models.GenericIPAddressField(help_text='IP地址', verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, help_text='SSH端口', verbose_name='SSH端口')),
                ('username', models.CharField(help_text='SSH登录用户名', max_length=256, verbose_name='SSH登录用户名')),
                ('password', models.CharField(help_text='SSH登录密码', max_length=256, verbose_name='SSH登录密码')),
                ('data_folder', models.CharField(default='/data', help_text='数据分区', max_length=256, verbose_name='数据分区')),
                ('service_num', models.IntegerField(default=0, help_text='服务个数', verbose_name='服务个数')),
                ('alert_num', models.IntegerField(default=0, help_text='告警次数', verbose_name='告警次数')),
                ('operate_system', models.CharField(help_text='操作系统', max_length=128, verbose_name='操作系统')),
                ('memory', models.IntegerField(blank=True, help_text='内存', null=True, verbose_name='内存')),
                ('cpu', models.IntegerField(blank=True, help_text='CPU', null=True, verbose_name='CPU')),
                ('disk', models.JSONField(blank=True, help_text='磁盘', null=True, verbose_name='磁盘')),
                ('host_agent', models.CharField(choices=[(0, '正常'), (1, '重启中'), (2, '异常'), (3, '部署中')], default=3, help_text='主机Agent状态', max_length=16, verbose_name='主机Agent状态')),
                ('monitor_agent', models.CharField(choices=[(0, '正常'), (1, '重启中'), (2, '异常'), (3, '部署中')], default=3, help_text='服务Agent状态', max_length=16, verbose_name='服务Agent状态')),
                ('is_maintenance', models.BooleanField(default=False, help_text='维护模式', verbose_name='维护模式')),
                ('env', models.ForeignKey(help_text='环境', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.env', verbose_name='环境')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'omp_host',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='HostOperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='操作用户', max_length=128, verbose_name='操作用户')),
                ('description', models.CharField(help_text='用户行为描述', max_length=1024, verbose_name='用户行为描述')),
                ('result', models.CharField(default='success', help_text='操作结果', max_length=1024, verbose_name='操作结果')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='发生时间', null=True, verbose_name='发生时间')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '主机操作记录',
                'verbose_name_plural': '主机操作记录',
                'db_table': 'omp_host_operate_log',
            },
        ),
        migrations.DeleteModel(
            name='Hosts',
        ),
        migrations.AlterModelOptions(
            name='operatelog',
            options={'verbose_name': '用户操作记录', 'verbose_name_plural': '用户操作记录'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='操作发生时间', verbose_name='操作发生时间'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='description',
            field=models.CharField(help_text='用户行为描述', max_length=256, verbose_name='用户行为描述'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, help_text='请求源IP', null=True, verbose_name='请求源IP'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='request_method',
            field=models.CharField(help_text='请求方法', max_length=32, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='request_result',
            field=models.CharField(default='success', help_text='请求结果', max_length=1024, verbose_name='请求结果'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='request_url',
            field=models.CharField(help_text='用户目标URL', max_length=256, verbose_name='用户目标URL'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='response_code',
            field=models.IntegerField(default=0, help_text='响应状态码', verbose_name='响应状态码'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='username',
            field=models.CharField(help_text='操作用户', max_length=128, verbose_name='操作用户'),
        ),
        migrations.AlterModelTable(
            name='operatelog',
            table='omp_user_operate_log',
        ),
    ]
