# Generated by Django 3.1.4 on 2021-09-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_auto_20210918_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_agent_error',
            field=models.CharField(blank=True, help_text='主机Agent异常信息', max_length=256, null=True, verbose_name='主机Agent异常信息'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_name',
            field=models.CharField(blank=True, help_text='主机名', max_length=64, null=True, verbose_name='主机名'),
        ),
        migrations.AddField(
            model_name='host',
            name='monitor_agent_error',
            field=models.CharField(blank=True, help_text='监控Agent异常信息', max_length=256, null=True, verbose_name='监控Agent异常信息'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_agent',
            field=models.CharField(choices=[(0, '正常'), (1, '重启中'), (2, '启动失败'), (3, '部署中'), (4, '部署失败')], default=3, help_text='主机Agent状态', max_length=16, verbose_name='主机Agent状态'),
        ),
        migrations.AlterField(
            model_name='host',
            name='monitor_agent',
            field=models.CharField(choices=[(0, '正常'), (1, '重启中'), (2, '启动失败'), (3, '部署中'), (4, '部署失败')], default=3, help_text='监控Agent状态', max_length=16, verbose_name='监控Agent状态'),
        ),
    ]
