# Generated by Django 3.1.4 on 2021-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_auto_20210922_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.IntegerField(default=0, help_text='此消息是否已读，0-未读；1-已读', verbose_name='已读')),
                ('alert_type', models.CharField(default='', help_text='告警类型，主机host，服务service', max_length=32, verbose_name='告警类型')),
                ('alert_host_ip', models.CharField(default='', help_text='告警来源主机ip', max_length=64, verbose_name='告警主机ip')),
                ('alert_host_instance_name', models.CharField(default='', help_text='告警主机实例名称', max_length=256, verbose_name='告警主机实例名称')),
                ('alert_service_name', models.CharField(default='', help_text='服务类告警中的服务名称', max_length=128, verbose_name='告警服务名称')),
                ('alert_service_instance_name', models.CharField(default='', help_text='告警服务实例名称', max_length=128, verbose_name='告警服务实例名称')),
                ('alert_service_type', models.CharField(default='', help_text='服务所属类型', max_length=128, verbose_name='告警服务类型')),
                ('alert_level', models.CharField(default='', help_text='告警级别', max_length=1024, verbose_name='告警级别')),
                ('alert_describe', models.CharField(default='', help_text='告警描述', max_length=1024, verbose_name='告警描述')),
                ('alert_receiver', models.CharField(default='', help_text='告警接收人', max_length=256, verbose_name='告警接收人')),
                ('alert_resolve', models.CharField(default='', help_text='告警解决方案', max_length=1024, verbose_name='告警解决方案')),
                ('alert_time', models.DateTimeField(help_text='告警发生时间', verbose_name='告警发生时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='告警信息入库时间', verbose_name='告警信息入库时间')),
                ('monitor_path', models.CharField(blank=True, help_text='跳转grafana路由', max_length=2048, null=True, verbose_name='跳转监控路径')),
                ('monitor_log', models.CharField(blank=True, help_text='跳转grafana日志页面路由', max_length=2048, null=True, verbose_name='跳转监控日志路径')),
                ('fingerprint', models.CharField(blank=True, help_text='告警的唯一标识', max_length=1024, null=True, verbose_name='告警的唯一标识')),
                ('env_id', models.IntegerField(default=1, help_text='环境id')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'db_table': 'omp_alert',
            },
        ),
    ]
