# Generated by Django 3.1.4 on 2021-09-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='监控类别', max_length=32, unique=True, verbose_name='监控类别')),
                ('monitor_url', models.CharField(help_text='请求地址', max_length=128, verbose_name='请求地址')),
            ],
            options={
                'verbose_name': '监控地址记录',
                'verbose_name_plural': '监控地址记录',
                'db_table': 'omp_promemonitor_url',
            },
        ),
    ]
