# Generated by Django 3.1.4 on 2021-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_auto_20211203_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='init_status',
            field=models.CharField(choices=[(0, '成功'), (1, '未执行'), (2, '执行中'), (3, '失败')], default=1, help_text='主机初始化状态', max_length=16, verbose_name='主机初始化状态'),
        ),
    ]
