# Generated by Django 3.1.4 on 2021-12-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_auto_20211203_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinstallhistory',
            name='name',
            field=models.CharField(default='初始化安装流程', help_text='名称', max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '启动中'), (2, '停止中'), (3, '重启中'), (4, '停止'), (5, '未知'), (6, '安装中'), (7, '安装失败'), (8, '待安装'), (9, '删除中')], default=5, help_text='服务状态', verbose_name='服务状态'),
        ),
        migrations.CreateModel(
            name='PostInstallHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(default='安装后续任务', help_text='名称', max_length=32, verbose_name='名称')),
                ('ip', models.CharField(default='postAction', help_text='主机ip地址', max_length=128, verbose_name='fake主机ip地址')),
                ('install_flag', models.IntegerField(default=0, help_text='0-待执行 1-执行中 2-执行成功 3-执行失败', verbose_name='安装标志')),
                ('install_log', models.TextField(help_text='安装后续任务日志', verbose_name='安装后续任务日志')),
                ('main_install_history', models.ForeignKey(blank=True, help_text='关联主安装记录', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.maininstallhistory')),
            ],
            options={
                'verbose_name': '后置安装记录',
                'verbose_name_plural': '后置安装记录',
                'db_table': 'omp_post_install_history',
            },
        ),
    ]
