# Generated by Django 3.1.4 on 2021-09-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_monitorurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matcher_name', models.CharField(help_text='匹配标签', max_length=1024, verbose_name='匹配标签')),
                ('matcher_value', models.CharField(help_text='匹配值', max_length=1024, verbose_name='匹配值')),
                ('maintain_id', models.CharField(help_text='维护唯一标识', max_length=1024, verbose_name='维护唯一标识')),
            ],
            options={
                'verbose_name': '维护记录',
                'verbose_name_plural': '维护记录',
                'db_table': 'omp_maintain',
            },
        ),
        migrations.RemoveField(
            model_name='alert',
            name='env_id',
        ),
        migrations.AddField(
            model_name='alert',
            name='env',
            field=models.ForeignKey(help_text='环境', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.env', verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='request_result',
            field=models.TextField(default='success', help_text='请求结果', verbose_name='请求结果'),
        ),
    ]
