# Generated by Django 3.1.4 on 2021-12-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_update_init_status'),
        ('db_models', '0005_auto_20211206_1723'),
    ]

    operations = [
    ]
