# Generated by Django 3.1.4 on 2021-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0006_auto_20210927_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='agent_dir',
            field=models.CharField(default='/data', help_text='Agent安装目录', max_length=256, verbose_name='Agent安装目录'),
        ),
    ]
