# Generated by Django 3.1.4 on 2021-09-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0007_host_agent_dir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostoperatelog',
            options={'ordering': ('-created',), 'verbose_name': '主机操作记录', 'verbose_name_plural': '主机操作记录'},
        ),
    ]
