# Generated by Django 3.1.4 on 2021-12-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0007_deploymentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vip',
            field=models.GenericIPAddressField(blank=True, default=None, help_text='vip地址', null=True, verbose_name='vip地址'),
        ),
    ]
