# Generated by Django 3.1.4 on 2021-12-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0008_service_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='instance_name',
            field=models.CharField(help_text='实例名', max_length=64, unique=True, verbose_name='实例名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP地址', unique=True, verbose_name='IP地址'),
        ),
    ]
