# Generated by Django 3.1.4 on 2021-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0009_app_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrafanaMainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(help_text='信息面板实例名字', max_length=32, unique=True, verbose_name='实例名字')),
                ('instance_url', models.CharField(help_text='实例文根地址', max_length=255, unique=True, verbose_name='实例地址')),
            ],
            options={
                'verbose_name': 'grafana面板记录',
                'verbose_name_plural': 'grafana面板记录',
                'db_table': 'omp_grafana_url',
            },
        ),
    ]
