# Generated by Django 3.1.4 on 2022-01-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0009_auto_20211228_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '启动中'), (2, '停止中'), (3, '重启中'), (4, '停止'), (5, '未知'), (6, '安装中'), (7, '安装失败'), (8, '待安装'), (9, '删除中'), (10, '升级中'), (11, '回滚中')], default=5, help_text='服务状态', verbose_name='服务状态'),
        ),
        migrations.CreateModel(
            name='UpgradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('upgrade_state', models.IntegerField(choices=[(0, '等待升级'), (1, '正在升级'), (2, '升级成功'), (3, '升级失败')], default=0, verbose_name='升级结果')),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.env', verbose_name='所属环境')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '升级历史记录',
                'verbose_name_plural': '升级历史记录',
                'db_table': 'omp_upgrade_history',
            },
        ),
        migrations.CreateModel(
            name='UpgradeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('upgrade_state', models.IntegerField(choices=[(0, '等待升级'), (1, '正在升级'), (2, '升级成功'), (3, '升级失败')], default=0, verbose_name='升级结果')),
                ('union_server', models.CharField(max_length=199, verbose_name='唯一服务实例:ip-app_name(适配hadoop，单服务裂开多个服务)')),
                ('path_info', models.JSONField(default=dict, verbose_name='服务包备份路径信息')),
                ('handler_info', models.JSONField(default=dict, verbose_name='升级步骤信息')),
                ('message', models.TextField(default='', verbose_name='升级日志信息')),
                ('has_rollback', models.BooleanField(default=False, verbose_name='是否已回滚')),
                ('current_app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_app_set', to='db_models.applicationhub', verbose_name='升级前服务')),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.upgradehistory', verbose_name='升级历史记录')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.service', verbose_name='服务')),
                ('target_app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_app_set', to='db_models.applicationhub', verbose_name='升级目标服务')),
            ],
            options={
                'verbose_name': '单个服务升级记录',
                'verbose_name_plural': '单个服务升级记录',
                'db_table': 'omp_upgrade_detail',
            },
        ),
        migrations.CreateModel(
            name='RollbackHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('rollback_state', models.IntegerField(choices=[(0, '等待回滚'), (1, '正在回滚'), (2, '回滚成功'), (3, '回滚失败')], default=0, verbose_name='回滚结果')),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.env', verbose_name='所属环境')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '回滚历史记录',
                'verbose_name_plural': '回滚历史记录',
                'db_table': 'omp_rollback_history',
            },
        ),
        migrations.CreateModel(
            name='RollbackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('rollback_state', models.IntegerField(choices=[(0, '等待回滚'), (1, '正在回滚'), (2, '回滚成功'), (3, '回滚失败')], default=0, verbose_name='回滚结果')),
                ('path_info', models.JSONField(default=dict, verbose_name='服务包备份路径信息')),
                ('handler_info', models.JSONField(default=dict, verbose_name='回滚步骤信息')),
                ('message', models.TextField(default='', verbose_name='回滚日志信息')),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.rollbackhistory', verbose_name='回滚历史记录')),
                ('upgrade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.upgradedetail', verbose_name='升级记录')),
            ],
            options={
                'verbose_name': '单个服务回滚记录',
                'verbose_name_plural': '单个服务回滚记录',
                'db_table': 'omp_rollback_detail',
            },
        ),
    ]
