# Generated by Django 3.1.4 on 2022-01-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0009_auto_20211228_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=128, verbose_name='备份任务名称')),
                ('content', models.JSONField(verbose_name='备份内容(服务名):["mysql","arangodb"]')),
                ('result', models.IntegerField(choices=[('成功', 1), ('备份中', 2), ('失败', 0)], default=2, verbose_name='结果')),
                ('message', models.JSONField(default=dict, verbose_name='返回信息')),
                ('file_name', models.CharField(default='', max_length=128, verbose_name='备份文件名')),
                ('file_size', models.CharField(default='0', max_length=64, verbose_name='备份文件大小, MB')),
                ('expire_time', models.DateTimeField(null=True, verbose_name='过期时间')),
                ('file_deleted', models.BooleanField(default=False, verbose_name='文件是否被删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录生成时间')),
                ('env_id', models.IntegerField(default=0, verbose_name='环境id')),
                ('retain_path', models.TextField(default='/data/backups/', verbose_name='文件保存路径')),
                ('operation', models.CharField(default='定时任务执行', max_length=32, verbose_name='操作方式')),
                ('send_email_result', models.IntegerField(choices=[('发送成功', 1), ('发送中', 2), ('发送失败', 0), ('未发送', 3)], default=3, verbose_name='邮件推送状态')),
                ('email_fail_reason', models.TextField(default='', verbose_name='邮件推送失败原因')),
            ],
            options={
                'verbose_name': '备份历史记录',
                'verbose_name_plural': '备份历史记录',
                'db_table': 'omp_backup_history',
            },
        ),
        migrations.CreateModel(
            name='BackupSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_service', models.JSONField(verbose_name='备份服务名称')),
                ('is_on', models.BooleanField(default=False, verbose_name='是否开启')),
                ('crontab_detail', models.JSONField(verbose_name='定时任务详情')),
                ('retain_day', models.IntegerField(default=1, verbose_name='文件保存天数')),
                ('retain_path', models.TextField(verbose_name='文件保存路径')),
                ('env_id', models.IntegerField(default=0, verbose_name='环境id')),
            ],
            options={
                'verbose_name': '备份设置',
                'verbose_name_plural': '备份设置',
                'db_table': 'omp_backup_setting',
            },
        ),
    ]
