# Generated by Django 3.1.4 on 2021-10-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0010_grafanamainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='label_type',
            field=models.IntegerField(choices=[(0, '组件'), (1, '应用')], default=0, help_text='标签类型', verbose_name='标签类型'),
        ),
    ]
