# Generated by Django 3.1.4 on 2022-01-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0010_backuphistory_backupsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupsetting',
            name='backup_service',
        ),
        migrations.AddField(
            model_name='backupsetting',
            name='backup_instances',
            field=models.JSONField(default=dict, verbose_name='备份服务实例名称'),
        ),
    ]
