# Generated by Django 3.1.4 on 2021-10-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0011_auto_20211012_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_host_instance_name',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_service_instance_name',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_instance_name',
            field=models.CharField(default='', help_text='告警实例名称', max_length=128, verbose_name='告警实例名称'),
        ),
    ]
