# Generated by Django 3.1.4 on 2021-10-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0012_auto_20211013_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpackagehistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='软删除'),
        ),
    ]
