# Generated by Django 3.1.4 on 2022-01-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0010_auto_20220114_1830'),
        ('db_models', '0012_auto_20220112_1653'),
    ]

    operations = [
    ]
