# Generated by Django 3.1.4 on 2021-10-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0013_uploadpackagehistory_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpackagehistory',
            name='package_status',
            field=models.IntegerField(
                choices=[
                    (0, '成功'),
                    (1, '失败'),
                    (2, '解析中'),
                    (3, '发布成功'),
                    (4, '发布失败'),
                    (5, '发布中')
                ], default=2, help_text='安装包状态', verbose_name='安装包状态'),
        ),
    ]
