# Generated by Django 3.1.4 on 2022-01-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0014_auto_20220121_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('module', models.CharField(choices=[('MainInstallHistory', '安装'), ('UpgradeHistory', '升级'), ('RollbackHistory', '回滚')], default='MainInstallHistory', max_length=32, verbose_name='执行记录的module名')),
                ('module_id', models.IntegerField(default=0, verbose_name='执行记录的id')),
                ('operator', models.CharField(default='admin', max_length=150, verbose_name='操作用户')),
                ('state', models.CharField(choices=[('INSTALL_STATUS_READY', '等待安装'), ('INSTALL_STATUS_INSTALLING', '正在安装'), ('INSTALL_STATUS_SUCCESS', '安装成功'), ('INSTALL_STATUS_FAILED', '安装失败'), ('INSTALL_STATUS_REGISTER', '正在注册'), ('UPGRADE_WAIT', '等待升级'), ('UPGRADE_ING', '正在升级'), ('UPGRADE_SUCCESS', '升级成功'), ('UPGRADE_FAIL', '升级失败'), ('ROLLBACK_WAIT', '等待回滚'), ('ROLLBACK_ING', '正在回滚'), ('ROLLBACK_SUCCESS', '回滚成功'), ('ROLLBACK_FAIL', '回滚失败')], default='INSTALL_STATUS_READY', max_length=32, verbose_name='状态')),
                ('count', models.IntegerField(default=0, verbose_name='服务数量')),
                ('end_time', models.DateTimeField(null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
                'db_table': 'omp_execution_record',
            },
        )
    ]
