# Generated by Django 3.1.4 on 2022-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0015_executionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrecord',
            name='module_id',
            field=models.CharField(default='0', max_length=36, verbose_name='执行记录的id'),
        )
    ]
