# Generated by Django 3.1.4 on 2021-10-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0015_inspectioncrontab_inspectionhistory_inspectionreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-created',), 'verbose_name': '服务实例表', 'verbose_name_plural': '服务实例表'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='product',
        ),
        migrations.RemoveField(
            model_name='service',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='inspectionhistory',
            name='inspection_status',
            field=models.IntegerField(default=0, help_text='巡检状态:1-进行中；2-成功；3-失败'),
        ),
    ]
