# Generated by Django 3.1.4 on 2022-01-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0016_auto_20220125_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfHealingSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False, verbose_name='是否启用')),
                ('alert_count', models.IntegerField(default=1, verbose_name='触发自愈的告警次数')),
                ('max_healing_count', models.IntegerField(default=5, verbose_name='最多自愈操作次数')),
                ('env', models.ForeignKey(help_text='环境', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.env', verbose_name='环境')),
            ],
            options={
                'verbose_name': '自愈设置',
                'verbose_name_plural': '自愈设置',
                'db_table': 'omp_self_healing_setting',
            },
        ),
        migrations.CreateModel(
            name='SelfHealingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.IntegerField(default=0, verbose_name='此消息是否已读，0-未读；1-已读')),
                ('host_ip', models.CharField(max_length=64, verbose_name='自愈主机ip')),
                ('service_name', models.CharField(default='', max_length=64, verbose_name='自愈服务名称')),
                ('instance_name', models.CharField(default='', help_text='自愈实例名称', max_length=128, verbose_name='自愈实例名称')),
                ('state', models.IntegerField(choices=[(2, '自愈中'), (0, '自愈失败'), (1, '自愈成功')], default=2, verbose_name='自愈状态')),
                ('healing_count', models.IntegerField(default=0, verbose_name='已运行自愈次数')),
                ('start_time', models.DateTimeField(null=True, verbose_name='自愈开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='自愈结束时间')),
                ('healing_log', models.JSONField(default=dict, verbose_name='自愈日志')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='关联告警唯一值')),
                ('alert_time', models.DateTimeField(null=True, verbose_name='关联告警时间，与fingerprint确定同一次告警')),
                ('alert_content', models.TextField(default='', verbose_name='告警日志内容')),
                ('monitor_log', models.TextField(default='', verbose_name='grafana日志url')),
                ('service_en_type', models.CharField(default='', max_length=64, verbose_name='服务类型，self_dev&component&database')),
                ('env', models.ForeignKey(help_text='环境', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.env', verbose_name='环境')),
            ],
            options={
                'verbose_name': '自愈历史记录',
                'verbose_name_plural': '自愈历史记录',
                'db_table': 'omp_self_healing_history',
            },
        ),
    ]
