# Generated by Django 3.1.4 on 2021-10-24 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0016_auto_20211023_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('product_instance_name', models.CharField(blank=True, help_text='安装产品时输入的实例名称', max_length=64, null=True, verbose_name='产品实例名称')),
                ('product', models.ForeignKey(blank=True, help_text='所属产品', null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.producthub')),
            ],
            options={
                'verbose_name': '产品实例表',
                'verbose_name_plural': '产品实例表',
                'db_table': 'omp_product_instance',
                'ordering': ('-created',),
            },
        ),
    ]
