# Generated by Django 3.1.4 on 2021-10-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0017_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='file_name',
            field=models.CharField(blank=True, help_text='导出文件名', max_length=128, null=True),
        ),
    ]
