# Generated by Django 3.1.4 on 2022-02-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0018_userloginlog_request_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='实用工具名称', max_length=128)),
                ('kind', models.IntegerField(choices=[(0, '管理工具'), (1, '检查工具'), (2, '安全工具'), (3, '其他工具')], default=0, help_text='实用工具分类', verbose_name='实用工具分类')),
                ('script_type', models.IntegerField(choices=[(0, 'python3'), (1, 'shell')], default=0, help_text='脚本类型', verbose_name='脚本类型')),
                ('target_name', models.CharField(default='host', help_text='脚本执行的目标对象', max_length=128, verbose_name='脚本执行的目标对象')),
                ('source_package_md5', models.CharField(blank=True, help_text='源码包md5值', max_length=32, null=True, verbose_name='源码包md5值')),
                ('source_package_path', models.CharField(max_length=128, verbose_name='源码包相对路径')),
                ('tool_folder_path', models.CharField(help_text='实用工具目录相对路径', max_length=128, verbose_name='实用工具目录相对路径')),
                ('script_path', models.CharField(help_text='脚本相对路径', max_length=128, verbose_name='脚本相对路径')),
                ('send_package', models.JSONField(default=list, help_text='需要发送的文件相对路径', max_length=128, verbose_name='需要发送的文件相对路径')),
                ('readme_info', models.TextField(blank=True, help_text='readme信息', null=True, verbose_name='readme信息')),
                ('template_filepath', models.JSONField(default=list, help_text='模板文件相对路径', verbose_name='模板文件相对路径')),
                ('obj_connection_args', models.JSONField(default=list, verbose_name='目标对象连接信息')),
                ('script_args', models.JSONField(default=list, verbose_name='脚本执行参数')),
                ('output', models.IntegerField(choices=[(0, '终端输出'), (1, '文件输出')], default=0, help_text='脚本的输出类型', verbose_name='脚本的输出类型')),
                ('description', models.TextField(help_text='描述信息', verbose_name='描述信息')),
            ],
            options={
                'verbose_name': '实用工具基本信息表',
                'verbose_name_plural': '实用工具基本信息表',
                'db_table': 'omp_tool_info',
            },
        ),
        migrations.CreateModel(
            name='UploadFileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('module', models.CharField(default='', max_length=32, verbose_name='需要上传文件的model')),
                ('module_id', models.IntegerField(default=0, verbose_name='需要上传文件的model id')),
                ('union_id', models.CharField(default='', max_length=64, verbose_name='文件md5值')),
                ('storage_klass', models.CharField(default='location', max_length=64, verbose_name='存储方式')),
                ('relative_path', models.TextField(default='', verbose_name='文件存储相对路径')),
                ('file_name', models.CharField(default='', max_length=64, verbose_name='文件名称')),
                ('file_size', models.CharField(default='0K', max_length=16, verbose_name='文件大小')),
                ('file_url', models.TextField(default='', verbose_name='文件访问路径')),
                ('deleted', models.BooleanField(default=False, verbose_name='删除')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '上传文件记录',
                'verbose_name_plural': '上传文件记录',
                'db_table': 'omp_upload_file',
            },
        ),
        migrations.CreateModel(
            name='ToolExecuteMainHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='任务标题', max_length=128, null=True, verbose_name='任务标题')),
                ('operator', models.CharField(blank=True, help_text='操作人', max_length=128, null=True, verbose_name='操作人')),
                ('status', models.IntegerField(choices=[(0, '待执行'), (1, '执行中'), (2, '执行成功'), (3, '执行失败')], default=0, help_text='main执行状态', verbose_name='main执行状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='开始时间', null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(help_text='结束时间', null=True, verbose_name='结束时间')),
                ('form_answer', models.JSONField(default=dict, verbose_name='任务表单提交结果')),
                ('tool', models.ForeignKey(help_text='实用工具对象', on_delete=django.db.models.deletion.CASCADE, to='db_models.toolinfo')),
            ],
            options={
                'verbose_name': '实用工具执行记录',
                'verbose_name_plural': '实用工具执行记录',
                'db_table': 'omp_tool_execute_main_history',
            },
        ),
        migrations.CreateModel(
            name='ToolExecuteDetailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('target_ip', models.CharField(help_text='目标IP地址', max_length=64, verbose_name='目标IP地址')),
                ('time_out', models.IntegerField(default=60, verbose_name='超时时间')),
                ('run_user', models.CharField(default='', max_length=64, verbose_name='执行用户')),
                ('status', models.IntegerField(choices=[(0, '待执行'), (1, '执行中'), (2, '执行成功'), (3, '执行失败'), (4, '执行超时')], default=0, help_text='detail执行状态', verbose_name='detail执行状态')),
                ('execute_args', models.JSONField(default=dict, help_text='执行参数信息', verbose_name='执行参数信息')),
                ('execute_log', models.TextField(help_text='执行日志', verbose_name='执行日志')),
                ('output', models.JSONField(default=dict, verbose_name='脚本输出内容')),
                ('main_history', models.ForeignKey(help_text='实用工具对象', on_delete=django.db.models.deletion.CASCADE, to='db_models.toolexecutemainhistory')),
            ],
            options={
                'verbose_name': '实用工具执行详情表',
                'verbose_name_plural': '实用工具执行详情表',
                'db_table': 'omp_tool_execute_detail_history',
            },
        ),
    ]
