# Generated by Django 3.1.4 on 2021-10-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0019_auto_20211025_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinstallhistory',
            name='install_detail_args',
            field=models.JSONField(blank=True, help_text='详情表安装信息', null=True, verbose_name='详情表安装信息'),
        ),
        migrations.AlterField(
            model_name='maininstallhistory',
            name='install_args',
            field=models.JSONField(blank=True, help_text='主表安装信息', null=True, verbose_name='主表安装信息'),
        ),
    ]
