# Generated by Django 3.1.4 on 2022-02-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0019_toolexecutedetailhistory_toolexecutemainhistory_toolinfo_uploadfilehistory'),
    ]

    operations = [
    ]
