# Generated by Django 3.1.4 on 2022-02-22 16:59

from django.db import migrations

from tool.find_tools import find_tools_package


def init_tools(apps, schema_editor):
    find_tools_package()


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0019_toolexecutedetailhistory_toolexecutemainhistory_toolinfo_uploadfilehistory'),
    ]

    operations = [
        migrations.RunPython(init_tools),
    ]
