# Generated by Django 3.1.4 on 2022-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0020_init_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('script_name', models.CharField(help_text='自定义脚本名称', max_length=32, verbose_name='脚本名称')),
                ('script_content', models.TextField(help_text='脚本内容', max_length=10000, verbose_name='脚本内容')),
                ('metrics', models.JSONField(help_text='指标列表', verbose_name='指标列表')),
                ('metric_num', models.IntegerField(help_text='metric数量', null=True, verbose_name='metric数量')),
                ('scrape_interval', models.IntegerField(default=60, help_text='prometheus探测周期', verbose_name='探测周期')),
                ('enabled', models.BooleanField(default=1, help_text='1位启用，0为禁用', verbose_name='是否启用')),
                ('description', models.TextField(help_text='脚本描述', max_length=1024, verbose_name='脚本描述')),
                ('bound_hosts', models.JSONField(help_text='已下发主机列表', verbose_name='已下发主机列表')),
            ],
            options={
                'verbose_name': '自定义脚本',
                'verbose_name_plural': '自定义脚本',
                'db_table': 'omp_custom_script',
            },
        ),
    ]
