# Generated by Django 3.1.4 on 2021-11-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0020_auto_20211026_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhub',
            name='is_base_env',
            field=models.BooleanField(default=False, help_text='是否为基础环境', verbose_name='是否为基础环境'),
        ),
    ]
