# Generated by Django 3.1.4 on 2021-11-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0021_applicationhub_is_base_env'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationhub',
            unique_together={('app_name', 'app_version')},
        ),
    ]
