# Generated by Django 3.1.4 on 2021-11-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0022_auto_20211103_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhub',
            name='app_monitor',
            field=models.JSONField(blank=True, help_text='监控使用字段', null=True, verbose_name='监控使用字段'),
        ),
        migrations.AddField(
            model_name='detailinstallhistory',
            name='post_action_flag',
            field=models.IntegerField(default=0, help_text='0-待执行 1-执行中 2-执行成功 3-执行失败 4-无需执行', verbose_name='安装后执行动作标记'),
        ),
        migrations.AddField(
            model_name='detailinstallhistory',
            name='post_action_msg',
            field=models.TextField(default='', help_text='安装后执行动作日志', verbose_name='安装后执行动作日志'),
        ),
        migrations.AddField(
            model_name='maininstallhistory',
            name='task_id',
            field=models.CharField(blank=True, help_text='异步任务id', max_length=36, null=True, verbose_name='异步任务id'),
        ),
    ]
