# Generated by Django 3.1.4 on 2022-02-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0022_alertrule_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ntpd_server',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='时间同步服务器地址'),
        ),
        migrations.AddField(
            model_name='host',
            name='ntpdate_install_status',
            field=models.CharField(choices=[(0, '执行成功'), (1, '未执行'), (2, '执行中'), (3, '执行失败')], default=1, max_length=16, verbose_name='安装ntpdate状态'),
        ),
        migrations.AddField(
            model_name='host',
            name='use_ntpd',
            field=models.BooleanField(default=False, verbose_name='是否开启时间同步服务'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_agent',
            field=models.CharField(choices=[(0, '正常'), (1, '重启中'), (2, '启动失败'), (3, '部署中'), (4, '部署失败'), (5, '删除中')], default=3, help_text='主机Agent状态', max_length=16, verbose_name='主机Agent状态'),
        ),
        migrations.AlterField(
            model_name='host',
            name='monitor_agent',
            field=models.CharField(choices=[(0, '正常'), (1, '重启中'), (2, '启动失败'), (3, '部署中'), (4, '部署失败'), (5, '删除中')], default=3, help_text='监控Agent状态', max_length=16, verbose_name='监控Agent状态'),
        ),
    ]
