# Generated by Django 3.1.4 on 2022-02-27 13:00
import os

from django.conf import settings
from django.db import migrations, models

from db_models.models import ToolInfo
from tool.find_tools import find_tools_package


def update_tool_logo(apps, schema_editor):
    tools = ToolInfo.objects.all()
    for tool in tools:
        folder_path = os.path.join(
            settings.PROJECT_DIR, "package_hub", tool.tool_folder_path
        )
        if os.path.exists(os.path.join(folder_path, 'logo.svg')):
            tool.logo = os.path.join(tool.tool_folder_path, 'logo.svg')
            tool.save()
    find_tools_package()


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0023_auto_20220225_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinfo',
            name='logo',
            field=models.URLField(default='', verbose_name='logo url'),
        ),
        migrations.RunPython(update_tool_logo),
    ]
