# Generated by Django 3.1.4 on 2021-11-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0023_auto_20211109_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSendWaySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False, verbose_name='是否启用')),
                ('env_id', models.IntegerField(default=0, verbose_name='环境id')),
                ('way_name', models.CharField(max_length=64, verbose_name='告警推送服务名称')),
                ('server_url', models.TextField(default='', verbose_name='告警推送服务url')),
                ('way_token', models.CharField(default='', max_length=255, verbose_name='服务token')),
                ('extra_info', models.JSONField(default=dict, verbose_name='服务其他信息')),
            ],
            options={
                'verbose_name': '告警推送通道设置',
                'verbose_name_plural': '告警推送通道设置',
                'db_table': 'omp_alert_send_way_setting',
            },
        ),
        migrations.CreateModel(
            name='EmailSMTPSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.EmailField(max_length=254, null=True, verbose_name='邮箱SMTP主机地址:smtp.163.com')),
                ('email_port', models.IntegerField(null=True, verbose_name='邮箱SMTP端口:465')),
                ('email_host_user', models.CharField(max_length=128, null=True, verbose_name='邮箱SMTP服务器用户名:a@163.com')),
                ('email_host_password', models.CharField(max_length=128, null=True, verbose_name='邮箱SMTP服务器秘钥')),
            ],
            options={
                'verbose_name': '平台邮件服务器配置',
                'verbose_name_plural': '平台邮件服务器配置',
                'db_table': 'omp_email_smtp_setting',
            },
        ),
    ]
