# Generated by Django 3.1.4 on 2021-11-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0024_alertsendwaysetting_emailsmtpsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSendEmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=64, verbose_name='功能模块:BackupSetting,JobSetting')),
                ('send_email', models.BooleanField(default=False, verbose_name='是否开启邮件推送')),
                ('to_users', models.TextField(default='', verbose_name='邮箱接收用户')),
                ('env_id', models.IntegerField(default=0, verbose_name='环境id')),
            ],
            options={
                'verbose_name': '平台邮件发送账号配置',
                'verbose_name_plural': '平台邮件发送账号配置',
                'db_table': 'omp_module_email_send_setting',
            },
        ),
    ]
