# Generated by Django 3.1.4 on 2022-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0024_auto_20220226_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='forbidden',
            field=models.IntegerField(default=1, verbose_name='禁止删除'),
        ),
    ]
