# Generated by Django 3.1.4 on 2022-03-03 15:27

from django.db import migrations, models
import django.db.models.manager
from db_models.models import Service


def combine_names(apps, schema_editor):
    for service in Service.objects.all():
        if service.service.app_name == "hadoop" and service.service_split == 0:
            if service.service_instance_name.startswith("hadoop"):
                service.service_split = 1
            else:
                service.service_split = 2
            service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0025_alertrule_forbidden'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
                ('split_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_split',
            field=models.IntegerField(choices=[(1, '拆分前'), (2, '拆分后'), (0, '未拆分')], default=0, help_text='拆分服务前对象',
                                      verbose_name='拆分服务前对象'),
        ),
        migrations.RunPython(combine_names)
    ]
