# Generated by Django 3.1.4 on 2022-03-03 15:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0025_alertrule_forbidden'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
                ('split_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_split',
            field=models.IntegerField(choices=[(1, '拆分前'), (2, '拆分后'), (0, '未拆分')], default=0, help_text='拆分服务前对象', verbose_name='拆分服务前对象'),
        ),
    ]
