# Generated by Django 3.1.4 on 2022-03-03 13:28

from django.db import migrations, models
from uuid import uuid4
from db_models.models import AlertRule
import hashlib


def get_hash_value(expr, severity):
    data = expr + severity
    hash_data = hashlib.md5(data.encode(encoding='UTF-8')).hexdigest()
    return hash_data


def update_hash_data(apps, schema_editor):
    alert_rulers = AlertRule.objects.all()
    for alert in alert_rulers:
        hash_data = get_hash_value(alert.expr, alert.severity)
        alert.hash_data = hash_data
        alert.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0025_alertrule_forbidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='hash_data',
            field=models.CharField(default=uuid4, unique=True, verbose_name='唯一hash值', max_length=255),
        ),
        migrations.RunPython(update_hash_data),
    ]
