# Generated by Django 3.1.4 on 2022-03-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0026_auto_20220303_1527'),
        ('db_models', '0026_alertrule_hash_data'),
    ]

    operations = [
    ]
