# Generated by Django 3.1.4 on 2021-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0027_inspectionhistory_send_email_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(help_text='指标项名称', max_length=64)),
                ('condition', models.CharField(help_text='阈值条件', max_length=32)),
                ('condition_value', models.CharField(help_text='阈值数值，百分号格式', max_length=128)),
                ('alert_level', models.CharField(help_text='告警级别', max_length=32)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('env_id', models.IntegerField(default=0, help_text='环境id')),
            ],
            options={
                'db_table': 'omp_host_threshold',
            },
        ),
        migrations.CreateModel(
            name='ServiceCustomThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64, verbose_name='服务名称')),
                ('index_type', models.CharField(max_length=64, verbose_name='指标项名称')),
                ('condition', models.CharField(max_length=32, verbose_name='阈值条件')),
                ('condition_value', models.CharField(max_length=128, verbose_name='阈值数值')),
                ('alert_level', models.CharField(max_length=32, verbose_name='告警级别')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('env_id', models.IntegerField(default=0, verbose_name='环境id')),
            ],
            options={
                'verbose_name': '服务定制指标阈值设置',
                'verbose_name_plural': '服务定制指标阈值设置',
                'db_table': 'omp_service_custom_threshold',
            },
        ),
        migrations.CreateModel(
            name='ServiceThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(max_length=64, verbose_name='指标项名称')),
                ('condition', models.CharField(max_length=32, verbose_name='阈值条件')),
                ('condition_value', models.CharField(max_length=128, verbose_name='阈值数值，百分号格式')),
                ('alert_level', models.CharField(max_length=32, verbose_name='告警级别')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('env_id', models.IntegerField(default=0, verbose_name='环境id')),
            ],
            options={
                'db_table': 'omp_service_threshold',
            },
        ),
    ]
