# Generated by Django 3.1.4 on 2023-01-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db_models', '0028_auto_20220304_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, help_text='用户角色', max_length=128, null=True, verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='hash_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='唯一hash值'),
        ),
    ]
