# Generated by Django 3.1.4 on 2021-11-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0028_hostthreshold_servicecustomthreshold_servicethreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininstallhistory',
            name='operator',
            field=models.CharField(default='admin', help_text='用户', max_length=32, verbose_name='操作用户'),
        ),
        migrations.AlterField(
            model_name='hostthreshold',
            name='env_id',
            field=models.IntegerField(default=1, help_text='环境id'),
        ),
        migrations.AlterField(
            model_name='modulesendemailsetting',
            name='env_id',
            field=models.IntegerField(default=1, verbose_name='环境id'),
        ),
        migrations.AlterField(
            model_name='servicecustomthreshold',
            name='env_id',
            field=models.IntegerField(default=1, verbose_name='环境id'),
        ),
        migrations.AlterField(
            model_name='servicethreshold',
            name='env_id',
            field=models.IntegerField(default=1, verbose_name='环境id'),
        ),
    ]
