# Generated by Django 3.1.4 on 2023-05-11 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0029_auto_20230110_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitSelfHealing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', max_length=64, verbose_name='自愈服务名称')),
                ('repair_ser', models.JSONField(default=dict, verbose_name='自愈缓存服务详情')),
                ('repair_status', models.IntegerField(default=0, verbose_name='自愈缓存服务')),
            ],
            options={
                'verbose_name': '自愈等待队列',
                'verbose_name_plural': '自愈等待队列',
                'db_table': 'omp_wait_self_healing',
            },
        ),
        migrations.RemoveField(
            model_name='selfhealinghistory',
            name='env',
        ),
        migrations.RemoveField(
            model_name='selfhealinghistory',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='selfhealinghistory',
            name='service_en_type',
        ),
        migrations.RemoveField(
            model_name='selfhealingsetting',
            name='alert_count',
        ),
        migrations.RemoveField(
            model_name='selfhealingsetting',
            name='env',
        ),
        migrations.AddField(
            model_name='selfhealingsetting',
            name='fresh_rate',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='周期内采集告警消息频次'),
        ),
        migrations.AddField(
            model_name='selfhealingsetting',
            name='instance_tp',
            field=models.IntegerField(choices=[(0, '启动'), (1, '重新启动')], default=0, verbose_name='实例类别'),
        ),
        migrations.AddField(
            model_name='selfhealingsetting',
            name='repair_instance',
            field=models.JSONField(default=dict, verbose_name='修复实例'),
        ),
        migrations.AlterField(
            model_name='backuphistory',
            name='retain_path',
            field=models.TextField(blank=True, default='/data/omp/data/backup/', max_length=256, null=True, verbose_name='文件保存路径'),
        ),
        migrations.AlterField(
            model_name='selfhealinghistory',
            name='healing_log',
            field=models.TextField(default='', verbose_name='自愈日志'),
        ),
        migrations.AlterField(
            model_name='selfhealingsetting',
            name='max_healing_count',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='最多自愈操作次数'),
        ),
    ]
