{
 "title": "RedisCluster 信息面板",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "集群",
    "query": {
     "query": "label_values(redis_uptime_in_seconds, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{cluster=\"$cluster\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "hits {{ instance_name }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "misses {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{cluster=~\"$cluster\"} ",
     "legendFormat": "used {{ instance_name }}"
    },
    {
     "expr": "redis_memory_max_bytes{cluster=~\"$cluster\"} ",
     "legendFormat": "max {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "input {{ instance_name }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{cluster=~\"$cluster\"}[5m])",
     "legendFormat": "output {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{cluster=~\"$cluster\"}) by (db)",
     "legendFormat": "{{ db }} {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{cluster=~\"$cluster\"}) - sum (redis_db_keys_expiring{cluster=~\"$cluster\"}) ",
     "legendFormat": "not expiring {{ instance_name }}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{cluster=~\"$cluster\"}) ",
     "legendFormat": "expiring {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{cluster=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "expired {{ instance_name }}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{cluster=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "evicted {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{cluster=~\"$cluster\"} [1m]))",
     "legendFormat": "{{ cmd }} {{ instance_name }}"
    }
   ]
  }
 ]
}