{
 "title": "Ignite 信息面板",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(ignite_started_thread_count,env)"
    }
   },
   {
    "name": "instance",
    "label": "instancce",
    "query": {
     "query": "label_values(ignite_started_thread_count{env=\"$env\"},instance)"
    }
   },
   { "name": "job", "label": "job", "query": "igniteExporter" }
  ]
 },
 "panels": [
  {
   "title": "UpTime ",
   "type": "stat",
   "description": "up time",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up_time{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "IgniteStartedThreadCount",
   "type": "bargauge",
   "description": "the num of started thread",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ignite_started_thread_count{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SentMessagesCount",
   "type": "stat",
   "description": "num of sent messages",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sent_messages_count{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "IgniteReceivedMessagesCount",
   "type": "stat",
   "description": "num of received messages",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ignite_received_messages_count{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "AverageJobWaitTime",
   "type": "graph",
   "description": "average time of job wait",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "average_job_wait_time{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CurrentJobWaitTime",
   "type": "graph",
   "description": "time of current job wait",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "current_job_wait_time{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "MaximumJobWaitTime",
   "type": "graph",
   "description": "max time of job wait",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "maximum_job_wait_time{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "AverageJobExecuteTime",
   "type": "graph",
   "description": "average time of job execute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "average_job_execute_time{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CurrentJobExecuteTime",
   "type": "graph",
   "description": "time of current job executed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_job_execute_time{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "MaximumJobExecuteTime",
   "type": "graph",
   "description": "max time of job execute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "maximum_job_execute_time{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "BusyTimePercentage",
   "type": "graph",
   "description": "busy time percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "busy_time_percentage{env=~\"$env\",instance=\"$instance\",job=\"$job\"}*100"
    }
   ]
  },
  {
   "title": "IgniteBusyTimeTotal",
   "type": "graph",
   "description": "total busy time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(total_busy_time{env=~\"$env\",instance=\"$instance\",job=\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "IgniteIdleTimeTotal",
   "type": "graph",
   "description": "total idle time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(ignite_idle_time_total{env=~\"$env\",instance=\"$instance\",job=\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "CurrentDaemonThreadCount",
   "type": "graph",
   "description": "current daemon thread count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_daemon_thread_count{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "MaximumThreadCount",
   "type": "graph",
   "description": "maximum thread count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "maximum_thread_count{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CurrentThreadCount",
   "type": "graph",
   "description": "current thread count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_thread_count{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  }
 ]
}