{
 "title": "Kafka 信息面板",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_brokers, job)"
    }
   },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(kafka_brokers, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_brokers{job=~\"$job\",env=\"$env\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "KafkaBrokers",
   "type": "stat",
   "description": "kafka brokers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{env=~\"$env\",instance=~\"$instance\",job=~\"kafkaExporter\"}"
    }
   ]
  },
  {
   "title": "ProcessOpenFds",
   "type": "graph",
   "description": "process open fds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{env=~\"$env\",instance=~\"$instance\",job=\"kafkaExporter\"}"
    }
   ]
  },
  {
   "title": "ProcessResidentMemoryBytes",
   "type": "graph",
   "description": "Resident memory size ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{env=~\"$env\",instance=~\"$instance\",job=\"kafkaExporter\"}"
    }
   ]
  },
  {
   "title": "ProcessCpuSecondsTotal",
   "type": "bargauge",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{env=~\"$env\",instance=~\"$instance\",job=\"kafkaExporter\"}"
    }
   ]
  },
  {
   "title": "kafkaTopicPartitions",
   "type": "graph",
   "description": "Number of partitions for this Topic",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partitions{env=~\"$env\",instance=~\"$instance\",job=\"kafkaExporter\"}"
    }
   ]
  },
  {
   "title": "KafkaTopicPartitionCurrentOffset",
   "type": "graph",
   "description": "kafka topic partition current offset",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{env=~\"$env\",instance=~'$instance'}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "KafkaTopicPartitionReplicas",
   "type": "graph",
   "description": "Number of Replicas for this Topic/Partition",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_replicas{env=~\"$env\",instance=~\"$instance\",job=\"kafkaExporter\"}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{env=~\"$env\",instance=\"$instance\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumergroup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{env=~\"$env$\",instance=~\"$instance$\"}) by (consumergroup)"
    }
   ]
  }
 ]
}