{
 "title": "Nacos 信息面板",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values({job=\"nacosExporter\"},env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"nacosExporter\",env=\"$env\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "nacos monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nacos_monitor{name=\"configCount\",env=\"$env\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "service count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='serviceCount',env=\"$env\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "ip count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='ipCount',env=\"$env\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "config count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='configCount',env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling',env=\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "config push total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='getConfig',env=\"$env\",instance=~\"$instance\"}) by (name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "<html>\n<body>\n<center>\n<a href=\"https://nacos.io\">\n<img src=\"https://nacos.io/img/nacos.png\" style=\"height: 50px;\" >\n</a>\n</center>\n</body>\n</html>"
   }
  },
  {
   "title": "cpu",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(system_cpu_usage{env=\"$env\",instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", env=\"$env\",instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\", env=~\"$env\",instance=~'$instance'}) * 100"
    }
   ]
  },
  { "title": "alert list", "type": "alertlist", "gridPos": { "h": 16, "w": 6, "x": 18, "y": 4 } },
  {
   "title": "threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{env=~\"$env\",instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(system_load_average_1m{env=~\"$env\",instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "notify rt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nacos_timer_seconds_sum{env=~\"$env\",instance=~'$instance'}[1m]))/sum(rate(nacos_timer_seconds_count{env=~\"$env\",instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "rt",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{env=~\"$env\",instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{env=~\"$env\",instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "qps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{env=~\"$env\",instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='avgPushCost', env=~\"$env\",instance=~'$instance'})"
    }
   ]
  },
  { "title": "nacos detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "rt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'/v1/cs/configs|/nacos/v1/ns', env=~\"$env\",instance=~'$instance'}[1m])/rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', env=~\"$env\",instance=~'$instance'}[1m])) by (method,uri) * 1000"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{env=~\"$env\",instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{env=~\"$env\",instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "repeat": "group",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling', env=~\"$env\",instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "load 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(system_load_average_1m{env=~\"$env\",instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', env=~\"$env\",instance=~'$instance'}[1m])) by (method,uri)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{env=~\"$env\",instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "leaderStatus",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='leaderStatus', env=~\"$env\",instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='avgPushCost', env=~\"$env\",instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "maxPushCost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='maxPushCost', env=~\"$env\",instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "config statistics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='publish', env=~\"$env\",instance=~'$instance'}) by (name)",
     "legendFormat": "publish config"
    },
    {
     "expr": "sum(nacos_monitor{name='getConfig', env=~\"$env\",instance=~'$instance'}) by (name)",
     "legendFormat": "get config"
    }
   ]
  },
  {
   "title": "health check",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_monitor{name=~'.*HealthCheck', env=~\"$env\",instance=~'$instance'}[1m])) by (name) * 60"
    }
   ]
  },
  { "title": "nacos alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "cpu alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(system_cpu_usage{env=~\"$env\",instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "load  alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(system_load_average_1m{env=~\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "memory alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",env=~\"$env\",instance=~\"$instance\"})/sum(jvm_memory_max_bytes{area=\"heap\",env=~\"$env\",instance=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "threads alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{env=~\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "gc alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\",env=~\"$env\",instance=~\"$instance\"}[5m])) * 300"
    }
   ]
  },
  {
   "title": "notify task alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='notifyTask',env=~\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "rt alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{env=~\"$env\",instance=~\"$instance\"}[1m]))/sum(rate(http_server_requests_seconds_count{env=~\"$env\",instance=~\"$instance\"}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "long polling alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='longPolling',env=~\"$env\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "failed push alert",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='failedPush',env=~\"$env\",instance=~\"$instance\"})"
    }
   ]
  }
 ]
}