{
 "title": "ZooKeeper 信息面板",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(zk_up,job)" } },
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(zk_up{job=~\"$job\"}, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(zk_up{job=~\"$job\",env=\"$env\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "leader",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "ms",
   "valueName": "name",
   "targets": [
    {
     "expr": "zk_server_leader{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_watch_count{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} watch_count"
    }
   ]
  },
  {
   "title": "open_file_descriptor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_znode_count{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} znode_count"
    },
    {
     "expr": "zk_ephemerals_count{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} ephemerals"
    }
   ]
  },
  {
   "title": "znode_count_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(zk_znode_count{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{instance}} znode_count_rate"
    },
    {
     "expr": "rate(zk_ephemerals_count{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{instance}} ephemerals_rate"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "zk_approximate_data_size{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} approximate_data_size"
    }
   ]
  },
  {
   "title": "num_alive_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_num_alive_connections{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} num_alive_connections"
    }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_received{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} packets_received"
    }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_packets_sent{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} packets_sent"
    }
   ]
  },
  {
   "title": "zk_outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} outstanding_changes_queued"
    }
   ]
  },
  {
   "title": "max_min_avg_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zk_min_latency{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} max_latency"
    },
    {
     "expr": "zk_max_latency{env=~\"$env\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} min_latency"
    },
    {
     "expr": "zk_avg_latency{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} avg_latency"
    }
   ]
  }
 ]
}