{
 "title": "JavaSpringBoot 信息面板",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(probe_success,env)"
    }
   },
   {
    "name": "ip",
    "label": "ip",
    "query": {
     "query": "label_values(probe_success{env=\"$env\"},instance)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(probe_success{env=\"$env\",instance=\"$ip\"},app)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(probe_success{env=\"$env\",instance=~\"$ip\",app=\"$app\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "服务状态",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{env=~\"$env\",instance=~\"$ip\",app=~\"$app\",app!=\"node\"}"
    }
   ]
  },
  {
   "title": "服务运行时间",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "cpu使用率",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"} * 100"
    }
   ]
  },
  {
   "title": "应用当前打开文件描述符数量",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_files_open_files{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "系统一分钟负载占用情况",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_average_1m{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "服务启动时间",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"} * 1000 "
    }
   ]
  },
  {
   "title": "Tomcat当前活跃session数量",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "应用可打开的最大文件描述符数量",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_files_max_files{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "JVM线程的当前数量",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "java虚拟机可用的cpu数量",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_gc_pause_seconds_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_count{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_gc_pause_seconds_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_gc_pause_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_sum{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_classes_loaded_classes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_gc_live_data_size_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes(nonheap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\",area=\"nonheap\"}"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes(heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\",area=\"heap\"}"
    }
   ]
  },
  {
   "title": "jvm_memory_max_bytes(nonheap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\",area=\"nonheap\"}"
    }
   ]
  },
  {
   "title": "jvm_memory_max_bytes(heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\",area=\"heap\"}"
    }
   ]
  },
  {
   "title": "jvm_memory_committed_bytes(nonheap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\",area=\"nonheap\"}"
    }
   ]
  },
  {
   "title": "jvm_memory_committed_bytes(heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\",area=\"heap\"}"
    }
   ]
  },
  {
   "title": "jvm_classes_unloaded_classes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_unloaded_classes_total{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_gc_max_data_size_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_max_data_size_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_threads_live_threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_buffer_memory_used_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_buffer_count_buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_threads_peak_threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Tomcat创建的session总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_created_sessions_total{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_gc_memory_promoted_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Tomcat过期的session总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_expired_sessions_total{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_buffer_total_capacity_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity_bytes{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Tomcat存活session最大数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_alive_max_seconds{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Tomcat最多活跃session数持续时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_max_sessions{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "jvm_gc_memory_allocated_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "超过session最大配置后，拒绝的session个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_rejected_sessions_total{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "日志级别事件个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "log4j2_events_total{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "http请求接口次数统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "http请求接口耗时统计",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{env=~\"$env\",instance=~\"$ip\",job=~\"$job\"}"
    }
   ]
  }
 ]
}