{
 "title": "ClickhouseCluster 信息面板",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "集群",
    "query": {
     "query": "label_values(clickhouse_query,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_query{cluster=~\"$cluster\"}[1m])"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_merge{cluster=~\"$cluster\"}",
     "legendFormat": "merge {{instance}}"
    },
    {
     "expr": "rate(clickhouse_merged_rows_total{cluster=~\"$cluster\"}[1m])",
     "legendFormat": "rate {{instance}}"
    }
   ]
  },
  {
   "title": "ReadOnly replica",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(clickhouse_readonly_replica{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_replicated_checks{cluster=~\"$cluster\"}"
    },
    {
     "expr": "clickhouse_replicated_fetch{cluster=~\"$cluster\"}"
    },
    {
     "expr": "clickhouse_replicated_send{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_read{cluster=~\"$cluster\"}"
    },
    {
     "expr": "clickhouse_write{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_background_pool_task{cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_tcp_connection{cluster=~\"$cluster\"}",
     "legendFormat": "tcp {{instance}}"
    },
    {
     "expr": "clickhouse_http_connection{cluster=~\"$cluster\"}",
     "legendFormat": "http {{instance}}"
    },
    {
     "expr": "clickhouse_interserver_connection{cluster=~\"$cluster\"}",
     "legendFormat": "interserver {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "clickhouse_memory_tracking{cluster=~\"$cluster\"}"
    }
   ]
  }
 ]
}