{
 "title": "TengineCluster (Nginx) 信息面板",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "集群",
    "query": {
     "query": "label_values(nginx_server_bytes,cluster)"
    }
   },
   {
    "name": "upstream",
    "label": "upstream",
    "query": {
     "query": "label_values(nginx_upstream_bytes{cluster=\"$cluster\"}, upstream)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_server_connections{cluster=~\"$cluster\",status=~\"active|writing|reading|waiting\"}",
     "legendFormat": "{{status}} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Server Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_cache{cluster=~\"$cluster\" }[5m])) by (status)",
     "legendFormat": "{{ status }} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_requests{cluster=~\"$cluster\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }} {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_server_bytes{cluster=~\"$cluster\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "graph",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_requests{cluster=~\"$cluster\", upstream=~\"^$upstream$\",code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }} {{ instance_name }}"
    }
   ]
  },
  {
   "title": "Upstream Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_upstream_bytes{cluster=~\"$cluster\", upstream=~\"^$upstream$\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }} {{instance_name}}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_upstream_responseMsec{cluster=~\"$cluster\", upstream=~\"^$upstream$\"}) by (backend)",
     "legendFormat": "{{ backend }} {{instance_name}}"
    }
   ]
  }
 ]
}