{
 "title": "rocketmq 信息面板",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(rocketmq_topic_retry_offset,env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(rocketmq_topic_retry_offset{env=\"$env\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(rocketmq_topic_retry_offset,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "broker tps & broker qps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_broker_tps{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_broker_qps{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "rocketmq_consumer_offset",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_consumer_offset{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "rocketmq_consumer_message_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_consumer_message_size{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "rocketmq_producer_offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_producer_offset{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "rocketmq_consumer_tps",
   "type": "graph",
   "description": "消费tps",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_consumer_tps{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "rocketmq_producer_message_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_producer_message_size{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "rocketmq_producer_tps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_producer_tps{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "rocketmq_group_get_latency_by_storetime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_group_get_latency_by_storetime{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "rocketmq_message_accumulation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset{env=~\"$env\",instance=\"$instance\",job=\"$job\"}) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset{env=~\"$env\",instance=\"$instance\",job=\"$job\"}) by (group,topic)"
    }
   ]
  },
  {
   "title": "PutMessageDistributeTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_pmdt_0ms{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_0to10ms{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_10to50ms{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_50to100ms{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_100to200ms{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_200to500ms{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_500to1s{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_1to2s{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_2to3s{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_3to4s{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_4to5s{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_5to10s{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_pmdt_10stomore{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "threadpoolqueue_headwait_timemills",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_pull_threadpoolqueue_headwait_timemills{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_query_threadpoolqueue_headwait_timemills{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_send_threadpoolqueue_headwait_timemills{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "consume client info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_client_consume_fail_msg_count{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_client_consume_fail_msg_tps{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_client_consume_ok_msg_tps{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_client_consume_rt{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_client_consumer_pull_rt{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_client_consumer_pull_tps{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "runtime tps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_getfound_tps10{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_gettotal_tps10{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_gettransfered_tps10{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_getmiss_tps10{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_put_tps10{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_commitlog_disk_ratio{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_consumequeue_disk_ratio{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlogdir_capacity_free{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlogdir_capacity_total{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlog_maxoffset{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_commitlog_minoffset{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "broker runtime info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_brokeruntime_msg_put_total_today_now{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_today_now{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_dispatch_behind_bytes{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_put_message_size_total{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_put_message_average_size{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_yesterdaymorning{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_puttotal_yesterdaymorning{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_gettotal_todaymorning{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "rocketmq_brokeruntime_msg_puttotal_todaymorning{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  }
 ]
}