{
 "title": "Arangodb 信息面板",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(arangodb_client_connection_statistics_client_connections,env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(arangodb_client_connection_statistics_client_connections{env=\"$env\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(arangodb_client_connection_statistics_client_connections,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RocksdbBaseLevel",
   "type": "gauge",
   "description": "rocksdb base level",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocksdb_base_level{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "ClientConnections",
   "type": "graph",
   "description": "The number of client connections that are currently open.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "UseSystemTime",
   "type": "stat",
   "description": "Amount of time that this process has been scheduled in kernel mode, measured in seconds.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_system_time{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "UseUserTime",
   "type": "stat",
   "description": "Amount of time that this process has been scheduled in user mode, measured in seconds.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_user_time{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RocksdbBackgroundErrors",
   "type": "stat",
   "description": "rocksdb background errors",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rocksdb_background_errors{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "ArangodbTransactionsStarted",
   "type": "stat",
   "description": "Transactions started",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "arangodb_transactions_started{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "ThreadNumbers",
   "type": "stat",
   "description": "Number of threads in the arangod process.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RocksdbCacheLimit",
   "type": "stat",
   "description": "rocksdb cache limit",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rocksdb_cache_limit{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RocksdbSizeAllMemTables",
   "type": "graph",
   "description": "rocksdb size all mem tables",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rocksdb_size_all_mem_tables{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RocksdbCacheAllocated",
   "type": "graph",
   "description": "rocksdb_cache_allocated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rocksdb_cache_allocated{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RocksdbNumSnapshots",
   "type": "gauge",
   "description": "rocksdb  snapshots num",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rocksdb_num_snapshots{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "ArangodbTransactionsCommitted",
   "type": "graph",
   "description": "Transactions committed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_transactions_committed{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RocksdbEstimateNumKeys ",
   "type": "graph",
   "description": "rocksdb estimate num keys",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocksdb_estimate_num_keys{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RocksdbActualDelayedWriteRate",
   "type": "graph",
   "description": "rocksdb actual delayed write rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rocksdb_actual_delayed_write_rate{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RocksdbCacheHitRateRecent",
   "type": "graph",
   "description": "rocksdb cache hit rate recent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rocksdb_cache_hit_rate_recent{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "ArangodbTransactionsAborted",
   "type": "graph",
   "description": "ransactions aborted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_transactions_aborted{env=~\"$env\",instance=~\"$instance\",job=\"$job\"}"
    }
   ]
  }
 ]
}