{
 "title": "Beanstalkd 信息面板",
 "templating": {
  "list": [
   { "name": "env", "label": "环境", "query": { "query": "label_values(total_jobs,env)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"beanstalkExporter\",env=\"$env\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UpTime",
   "type": "stat",
   "description": "up time",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{job=\"beanstalkExporter\",env=~\"$env\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SysCpuTime",
   "type": "stat",
   "description": "sys cpu time",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rusage_stime{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "UserCpuTime",
   "type": "stat",
   "description": "user cpu time",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rusage_utime{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "TotalConnections",
   "type": "bargauge",
   "description": "total connections",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "total_connections{job=\"beanstalkExporter\",env=~\"$env\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "TotalJobs",
   "type": "graph",
   "description": "total jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_jobs{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "BuriedJobs",
   "type": "graph",
   "description": "buried jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_jobs_buried{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "DelayedJobs",
   "type": "graph",
   "description": "delayed jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "current_jobs_delayed{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "TimeoutJobNum",
   "type": "graph",
   "description": "num of timeout job",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job_timeouts{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "StatsCmdNum",
   "type": "graph",
   "description": "num of stats cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_stats{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "ReverseCmdNum",
   "type": "graph",
   "description": "num of reverse cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_reserve{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "ReleaseCmdNum",
   "type": "graph",
   "description": "num of release cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_release{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "PutCmdNum",
   "type": "graph",
   "description": "num of put cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_put{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "PeekCmdNum",
   "type": "graph",
   "description": "num of peek cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_peek{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "KickCmdNum",
   "type": "graph",
   "description": "num of kick cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_kick{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "IgnoreCmdNum",
   "type": "graph",
   "description": "num of ignore cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_ignore{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "DeleteCmdNum",
   "type": "graph",
   "description": "num of delete cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_delete{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  },
  {
   "title": "BuryCmdNum",
   "type": "graph",
   "description": "num of bury cmd ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd_bury{env=~\"$env\",instance=\"$instance\",job=\"beanstalkExporter\"}"
    }
   ]
  }
 ]
}