{
 "title": "Clickhouse 信息面板",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(clickhouse_query,env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(clickhouse_query{env=\"$env\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(clickhouse_query,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(clickhouse_query{env=~\"$env\",instance=\"$instance\",job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_merge{env=~\"$env\",instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "merge {{job}}"
    },
    {
     "expr": "rate(clickhouse_merged_rows_total{env=~\"$env\",instance=\"$instance\",job=\"$job\"}[1m])",
     "legendFormat": "rate {{job}}"
    }
   ]
  },
  {
   "title": "ReadOnly replica",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(clickhouse_readonly_replica{env=~\"$env\",instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_replicated_checks{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "clickhouse_replicated_fetch{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "clickhouse_replicated_send{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_read{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    },
    {
     "expr": "clickhouse_write{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_background_pool_task{env=~\"$env\",instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clickhouse_tcp_connection{env=~\"$env\",instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "tcp {{instance}}"
    },
    {
     "expr": "clickhouse_http_connection{env=~\"$env\",instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "http {{instance}}"
    },
    {
     "expr": "clickhouse_interserver_connection{env=~\"$env\",instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "interserver"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "clickhouse_memory_tracking{env=~\"$env\",instance=\"$instance\",job=\"$job\"}"
    }
   ]
  }
 ]
}