{
 "title": "Httpd 信息面板",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values({job=\"httpdExporter\"}, env)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({job=\"httpdExporter\",env=\"$env\"}, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values({job=\"httpdExporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Apache Up / Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(apache_up{env=~\"$env\",instance=~\"$host\"} == 1)",
     "legendFormat": "Apache Up"
    }
   ]
  },
  {
   "title": "process_max_fds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{env=~\"$env\",instance=~\"$host\",job=\"httpdExporter\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{env=~\"$env\",instance=~\"$host\",job=\"httpdExporter\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "apache_accesses_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_accesses_total{env=~\"$env\",instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "apache_cpuload",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_cpuload{env=\"$env\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "apache_workers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "apache_workers{env=\"$env\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "apache_uptime_seconds_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{env=\"$env\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "http_request_size_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_size_bytes{env=\"$env\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "http_request_size_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_response_size_bytes{env=\"$env\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "apache_scoreboard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_scoreboard{env=\"$env\",instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_microseconds{env=\"$env\",instance=\"$host\"}"
    }
   ]
  }
 ]
}