# Generated by Django 3.1.4 on 2021-10-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='inst_id',
            field=models.ForeignKey(help_text='巡检记录历史表id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.inspectionhistory', unique=True, verbose_name='巡检记录历史表'),
        ),
    ]
