# Generated by Django 3.1.4 on 2021-10-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20211015_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='inst_id',
            field=models.OneToOneField(help_text='巡检记录历史表id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.inspectionhistory', verbose_name='巡检记录历史表'),
        ),
    ]
