#!/bin/bash

HELP_MSG="
此脚本具体使用命令如下:\n
1. 删除已纳管的主机及服务操作:\n
\t bash cmd_manager uninstall\n
2. 产品安装操作(使用excel模板进行安装)\n
\t bash cmd_manager install [excel的绝对路径(不填写默认寻找与OMP同级目录下的deployment.xlsx)]\n
3. 产品的升级\n
\t bash cmd_manager upgrade [xxx]
"

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
THIS_SCRIPT="${CURRENT_DIR}/$(basename $0)"
PROJECT_FOLDER="$(dirname ${CURRENT_DIR})"

# 解决openssl依赖的问题
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${PROJECT_FOLDER}/component/env/lib/

PYTHON3="${PROJECT_FOLDER}/component/env/bin/python3"
UNINSTALL_SERVICE_PATH="${PROJECT_FOLDER}/scripts/source/uninstall_services.py"
INSTALL_SERVICE_PATH="${PROJECT_FOLDER}/scripts/source/cmd_install_entrance.py"

function help() {
  echo -e $HELP_MSG
}

function install() {
  $PYTHON3 $INSTALL_SERVICE_PATH --excel_path=$1
}

function uninstall_all_service_and_host() {
  for i in $(seq 1 3)
  do
    read -p "删除已部署的服务?确认请第${i}请再次输入delete or DELETE > " ask
    if [[ "$ask" == "delete" ]] || [[ "$ask" == "DELETE" ]];then
      continue
    fi
    exit 1
  done
  $PYTHON3 $UNINSTALL_SERVICE_PATH
  if [[ $? -ne 0 ]];then
    echo "卸载已部署的服务失败"
    exit 1
  fi
  echo "卸载已部署的服务成功"
}

if [[ $# -eq 0 ]]; then
  # echo "bash cmd_manager [uninstall|install|upgrade|rollback] [...]"
  help
else
  case $1 in
  help)
    shift
    help "$@"
    ;;
  uninstall)
    shift
    uninstall_all_service_and_host "$@"
    ;;
  install)
    shift
    install "$@"
    ;;
  *)
    shift
    help "#@"
  esac
fi
