#!/bin/bash

# uwsgi的控制脚本

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
THIS_SCRIPT="${CURRENT_DIR}/$(basename $0)"
PROJECT_FOLDER="$(dirname $(dirname ${CURRENT_DIR}))"

APP_NAME="uwsgi"

start() {
  real_status
  if [ $? -eq 0 ];then
    echo "${APP_NAME} [running]"
    return 0
  else
    $PROJECT_FOLDER/component/env/bin/uwsgi --ini $PROJECT_FOLDER/config/uwsgi.ini >/dev/null  2>&1
    echo "${APP_NAME} [running]"
  fi
}

stop() {
  real_status
  if [ $? -eq 1 ]; then
    echo "${APP_NAME} [not running]"
    return 0
  else
    ps -ef | grep "${PROJECT_FOLDER}/component/env/bin/uwsgi" | grep -v grep | cut -c 9-15 | xargs kill -9
    sleep 3
    real_status
    if [ $? -eq 0 ]; then
      echo "${APP_NAME} [running]"
      return 1
    else
      echo "${APP_NAME} [not running]"
      return 0
    fi
  fi
}

real_status() {
  uwsgi_status=$(ps -ef | grep ${PROJECT_FOLDER}/component/env/bin/uwsgi | grep -v grep)
  if [ -n "$uwsgi_status" ]; then
    return 0
  else
    return 1
  fi
}

status() {
  real_status
  if [ $? -eq 0 ]; then
    echo "${APP_NAME} [running]"
    return 0
  else
    echo "${APP_NAME} [not running]"
    return 1
  fi
}

case $1 in
start) start ;;
stop) stop ;;
restart)
  stop
  start
  ;;
status)
  status
  ;;
*)
  echo "usage: $0 [start|stop|restart|status]"
  ;;
esac
