export const CHANGE_DATASOURCE = "CHANGE_DATASOURCE";

export const CHANGE_IPLIST = "CHANGE_IPLIST";

export const CHANGE_STEP1DATA = "CHANGE_STEP1DATA";

export const CHANGE_STEP2DATA = "CHANGE_STEP2DATA";

export const CHANGE_STEP3DATA = "CHANGE_STEP3DATA";